version: '3'
services:
  datomicdb:
    build:
      context: ./docker
      dockerfile: ./db.Dockerfile
    ports:
      - "4334:4334"
      - "4335:4335"
      - "4336:4336"
    volumes:
      - "/data"
